title: "Rainbowsight" 
description: "A Family of A Family of Generalizable, Curved, Camera-Based Tactile Sensors for Shape Reconstruction"
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: false
