title: "Rainbowsight" 
description: "A Family of A Family of Generalizable, Curved, Camera-Based Tactile Sensors for Shape Reconstruction <br> Megha H. Tippur and Edward H. Adelson" 
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: false
