title: "Rainbowsight: A Family of A Family of Generalizable, Curved, Camera-Based Tactile Sensors for Shape Reconstruction" 
description: "<a href='mailto:Megha Tippur'>Megha H. Tippur</a> and Edward H. Adelson"
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: false
